### ISSUE TITLE
Link of blog post

### ISSUE THREAD

**Issue by cedk** [openlabs/tryton.us#119]
When clicking on a blog post link from the blog index, we don't land directly to the post but on the top of tha page where there is a big image that take the all place, so we have to scroll to start reading.
The link should land directly to the article.

**Comment by rituparnapanda** [comment]
@gautampanday I think when we click a particular blog to read, we should land to the heading and not the banner on the page. Can you please take reference from the screenshot below:

![screenshot 2015-03-03 15 40 54](https://cloud.githubusercontent.com/assets/2655038/6460261/b280e588-c1bb-11e4-8747-f31a5da7a82d.png)

**Comment by rituparnapanda** [comment]
Issue is fixed with this commit : 115c7988b8af588c86d597d86c3ee56919ec5cd3
