### ISSUE TITLE
one of the active Open source communities in the world

### ISSUE THREAD

**Issue by cedk** [openlabs/tryton.us#124]
I really doubt about this statement.

**Comment by nicoe** [comment]
It's true, but it is useless.

**Comment by cedk** [comment]
Yes, but I think the author wanted to say "one of the most active" otherwise the sentence is weird.

**Comment by cedk** [comment]
So now, it is a clear wrong statement and lie. I can name thousand of open source projects that have a more active community.
So I really think there is a huge gap between your goal with this website and the goal of the Tryton's community.

**Comment by cedk** [comment]
By the way, I can even not re-open this issue. This platform really sucks.
