### ISSUE TITLE
Opensource vs Open Source vs Open-source

### ISSUE THREAD

**Issue by cedk** [openlabs/tryton.us#134]
Which version to use is an open discussion but the site should always use the same version.
Personally, I prefer "Open Source".

**Comment by rituparnapanda** [comment]
@cedk I also prefer "Open Source" :-)

I think it is written this way on the website as well. Did you find it different anywhere ?

**Comment by cedk** [comment]
At least on the title of the index page.

**Comment by rituparnapanda** [comment]
This has been fixed : bd86a748b350557e70b8fb7c5fda35366333f009
