### ISSUE TITLE
Use 'split button' dropdowns instead of 'single button' dropdowns

### ISSUE THREAD

**Issue by pilou-** [openlabs/tryton.us#76]
The top right navbar could use 'split button' dropdowns instead of 'single button' dropdowns in order to avoid a repetition.

Single button dropdowns:
![Single button dropdowns](http://i.imgur.com/kwW0Gvq.png)
Split button dropdowns ([implementation](https://github.com/pilou-/tryton.us/tree/button_dropdown)):
![Split button dropdowns](http://i.imgur.com/sRRV4GG.png)

**Comment by rituparnapanda** [comment]
This has been fixed. I am closing this issue.
